# Exa
# alias ls='exa --group-directories-first --icons'
# alias l='ls -blF --icons'
# alias ll='ls -al --icons'
# alias lt='exa -a -T -L=1 --icons'
alias ls='exa --group-directories-first'
alias l='ls -blF'
alias ll='ls -al'
alias llm='ll --sort=modified'
alias la='ls -abghilmu'
alias lx='ls -abghilmuHSU@'
alias lt='exa -a -T -L=1'