#yarn
alias y="yarn"
alias ya="yarn add"
alias yi="yarn install"
alias yr="yarn remove"
alias yu="yarn upgrade"
alias yad="yarn add -D"
alias yd="yarn dev"
alias ys="yarn start"
alias yw="yarn  watch"
alias yws="yarn watch-bs"
alias yb="yarn build"
alias yp="yarn production"